project 'RockSportReborn.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RockSportReborn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RockSportReborn
    pod 'Google-Mobile-Ads-SDK'
    pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  target 'RockSportRebornTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RockSportReborn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RockSportReborn-tvOS

  target 'RockSportReborn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
